packages/schemas/src/player/gamemodes/arcade/mode.ts
- Mini Walls Kit: the default value is "Soldier" in api and not "None"
- Hypixel Says Rounds: This is mislabeled in api and is actually the total points the player has earned
Most of these are self explanatory, if you have any questions please ask.
=> Add more relavent arcade stats

packages/schemas/src/player/gamemodes/paintball/index.ts, packages/schemas/src/player/gamemodes/paintball/perks.ts
Added all the perks for paintball and added the hat that the player uses
=> feat(paintball): add more stats and perks

packages/schemas/src/guild/index.ts, packages/schemas/src/guild/member.ts, packages/schemas/src/guild/rank.ts, packages/schemas/src/guild/util.ts
=> feat(guild): add the rest of the default guild data

.husky/pre-commit, apps/api/package.json, package.json, packages/logger/package.json, packages/math/package.json, packages/schemas/package.json, packages/schemas/src/index.ts, packages/util/package.json, tsconfig.base.json, turbo.json
Added husky hooks and scripts to check types.
=> ci(husky): Added husky hooks

.eslintrc, .gitignore, apps/api/tsconfig.eslint.json, apps/site/next-env.d.ts, apps/site/next.config.js, apps/site/package.json, apps/site/pages/index.tsx, apps/site/tsconfig.eslint.json, apps/site/tsconfig.json, package.json, packages/logger/tsconfig.eslint.json, packages/math/tsconfig.eslint.json, packages/schemas/tsconfig.eslint.json, packages/util/tsconfig.eslint.json, tsconfig.base.json, tsconfig.eslint.json, turbo.json, yarn.lock
Creates a basic nextjs app and refactors some eslint settings.
=> feat(site): create initial site app

apps/api/package.json, apps/api/src/app.module.ts, apps/api/src/dtos/historical-type.dto.ts, apps/api/src/dtos/historical.dto.ts, apps/api/src/historical/historical-type.enum.ts, apps/api/src/historical/historical.controller.ts, apps/api/src/historical/historical.module.ts, apps/api/src/historical/historical.service.ts, apps/api/src/historical/models/daily.model.ts, apps/api/src/historical/models/monthly.model.ts, apps/api/src/historical/models/weekly.model.ts, apps/api/src/leaderboards/leaderboard.controller.ts, apps/api/src/player/player.service.ts, apps/api/tsconfig.json, yarn.lock
=> feat(historical): add historical stats routes and logic

apps/api/src/historical/historical-type.enum.ts, apps/api/src/historical/historical.module.ts, apps/api/src/historical/historical.service.ts, apps/api/src/historical/models/index.ts, apps/api/src/historical/models/last-day.model.ts, apps/api/src/historical/models/last-month.model.ts, apps/api/src/historical/models/last-week.model.ts
=> feat(historical): added last day, week, and month historical stats

packages/schemas/src/player/gamemodes/blitzsg/index.ts, packages/schemas/src/player/gamemodes/blitzsg/kit.ts
Description: Fixed Leveling and the Shark + Milkman Kit.
Related issues (if exists): closes #33
=> feat(blitz): added Shark + Milkman Kit & Fixed Leveling

packages/schemas/src/player/gamemodes/quake/index.ts, packages/schemas/src/player/gamemodes/skywars/index.ts
Description: Fixes quake ratios and skywars doubles stats
=> fix(schema): Fix quake ratios + skywars doubles

apps/api/src/dtos/index.ts, apps/api/src/dtos/player-rankings.dto.ts, apps/api/src/player/leaderboards/player-leaderboard.controller.ts, apps/api/src/player/leaderboards/player-leaderboard.service.ts, apps/api/src/responses/post.player-rankings.response.ts
Description: Adds player rankings that use redis pipelining.
=> feat(rankings): add player rankings

.github/workflows/ci.yml, .gitignore, apps/api/package.json, codecov.yml, package.json, packages/logger/package.json, packages/math/package.json, packages/schemas/package.json, packages/util/package.json, turbo.json
Description: Adds code coverage
=> chore(coverage): add code coverage

.vscode/settings.json, apps/api/src/app.controller.ts, apps/api/src/guild/guild.controller.ts, apps/api/src/historical/historical.controller.ts, apps/api/src/hypixel-resources/hypixel-resources.controller.ts, apps/api/src/player/leaderboards/player-leaderboard.controller.ts, apps/api/src/player/player.controller.ts, apps/api/src/skin/skin.controller.ts, apps/api/views/redoc.handlebars
Description: Change Redoc from Light Theme to "Tokyo Night" vibe
=> docs(redoc): change Redoc from Light Theme to "Tokyo Night" vibe

packages/math/tests/index.spec.ts
Description: add more math tests such as radians and missing situations
=> test(math): add more math tests such as radians and missing situations

packages/math/tests/index.spec.ts, packages/util/tests/index.spec.ts
Description: Adding missing tests or correcting existing tests
=> test(utils): Adding missing util tests

packages/math/src/index.ts, packages/schemas/src/util/deserialize.ts, packages/schemas/src/util/get-leaderboard-field.ts, packages/schemas/src/util/get-leaderboard-fields.ts, packages/schemas/src/util/serialize.ts, packages/schemas/src/util/shared.ts, packages/util/src/index.ts, packages/util/tests/index.spec.ts
Description: move getConstructor to utils, cleaning up code
=> refactor(constructor): move getConstructor to utils

.github/workflows/ci.yml
Description: Fixes ci so that when coverage fails the whole ci does not.
=> fix(ci): make coverage not fail the ci

apps/api/src/guild/guild.service.ts, apps/api/src/player/player.controller.ts, apps/api/src/player/player.service.ts, packages/schemas/src/guild/index.ts, packages/schemas/src/guild/member.ts
Description: Collect monthly gexp data and add fields for totals. This pr also adds a delete player route
Related issues (if exists): closes #30
=> feat(guild monthly, player): monthly gexp and delete route

packages/math/src/index.ts, packages/schemas/src/util/deserialize.ts, packages/schemas/src/util/get-leaderboard-field.ts, packages/schemas/src/util/get-leaderboard-fields.ts, packages/schemas/src/util/serialize.ts, packages/schemas/src/util/shared.ts, packages/util/src/index.ts, packages/util/tests/index.spec.ts
Description: add more casing support to the prettier function
=> fix/prettierFunc: add more casing support to the prettier function

apps/api/src/dtos/index.ts, apps/api/src/historical/historical.controller.ts, apps/api/src/hypixel/hypixel.service.ts, apps/api/src/player/player.controller.ts, apps/api/src/player/player.service.ts, apps/api/src/responses/get.achievements.response.ts, apps/api/src/responses/index.ts, packages/schemas/src/achievements/game.ts, packages/schemas/src/achievements/iachievement.ts, packages/schemas/src/achievements/index.ts, packages/schemas/src/achievements/one-time-achievement.ts, packages/schemas/src/achievements/tiered-achievement.ts, packages/schemas/src/decorators/field.ts, packages/schemas/src/index.ts, packages/schemas/src/player/index.ts, packages/schemas/src/util/deserialize.ts, packages/schemas/src/util/serialize.ts
Description: adds an achievements route and stores achievements in mongo
Related issues (if exists): closes #32
=> feat(achievements): added an achievements route

packages/discord/src/command/abstract-command.listener.ts, packages/schemas/src/achievements/index.ts
Description: Fixes Interaction Server with a port not working as well as some sorting and spelling changes
=> fix(discord bot): Fix Interaction Server with a port not working

apps/api/views/redoc.handlebars
Description: change background color of redoc authentication table
=> docs(redoc): change background color of redoc authentication table

apps/discord-bot/package.json, apps/discord-bot/src/command.listener.ts, apps/discord-bot/src/commands/example.command.ts, packages/discord/src/command/command.context.ts, packages/discord/src/embed/index.ts, packages/discord/src/index.ts, packages/discord/src/interaction/interaction.content.ts, packages/discord/src/interaction/interaction.ts, packages/discord/tests/embed.builder.spec.ts, yarn.lock
Description: adds more utility functions to `CommandContext` and for more message responses
=> feat(discord): add more functionality to `CommandContext`

apps/discord-bot/package.json, packages/discord/src/interaction/interaction.ts, packages/schemas/src/index.ts, packages/schemas/src/user/index.ts, yarn.lock
Description: Creates the `User` schema to be stored in mongo.
=> feat(user): add `User` schema to `@statsify/schemas`

packages/schemas/src/player/gamemodes/copsandcrims/index.ts, packages/schemas/src/player/gamemodes/copsandcrims/mode.ts
Description:
The cvc stats were incomplete and found to be lacking two of the gamemodes. This pr aims to implement a better data format for the entire game.
=> feat(cvc): rework data format for cvc

packages/schemas/src/player/index.ts, packages/schemas/src/player/status.ts
Adds alot more data on players current status.
=> feat(player): add player status info

apps/api/src/auth/auth.guard.ts, apps/api/src/auth/auth.service.ts, apps/api/tests/mocks/auth.mock.ts
Adds headers with data on the users api key
=> feat(api): add key data headers to api response

.eslintrc, apps/scripts/package.json, apps/scripts/src/test.js, package.json, yarn.lock
Description: init scripts for vampire z number
=> chore(scripts): init scripts for vampirez number

apps/scripts/package.json, apps/scripts/src/create-key.mjs, apps/scripts/src/test.js, yarn.lock
Description: a script for creating statsify api keys
=> feat(create key): a script for creating statsify api keys

apps/api/src/leaderboards/leaderboard.service.ts, apps/api/src/player/leaderboards/player-leaderboard.service.ts, packages/schemas/src/player/gamemodes/megawalls/kit.ts
Description: add ASC sorting for leaderboards && points for MW kits
=> feat(leaderboards): add ASC sort for lb & points for MW kits

.env.schema, apps/discord-bot/src/command.listener.ts, apps/discord-bot/src/module.d.ts, locales/en-US/discord-bot/default.json, packages/discord/src/command/command.interface.ts, packages/discord/src/command/command.resolvable.ts, packages/discord/src/messages/error.message.ts, packages/schemas/src/user/index.ts
Add basic cooldowns
Closes #144
=> feat: add cooldowns

apps/discord-bot/.swcrc, apps/discord-bot/src/commands/bedwars.command.tsx, apps/discord-bot/src/commands/skywars.command.tsx, apps/discord-bot/src/components/Container.tsx, apps/discord-bot/src/components/Footer.tsx, apps/discord-bot/src/components/Header/Header.tsx, apps/discord-bot/src/components/Header/HeaderNametag.tsx, apps/discord-bot/src/components/If.tsx, apps/discord-bot/src/profiles/base.profile.ts, apps/discord-bot/src/profiles/bedwars.profile.tsx, apps/discord-bot/src/profiles/skywars.profile.tsx, apps/discord-bot/src/services/api.service.ts, apps/discord-bot/src/services/i18next.service.ts, apps/discord-bot/tsconfig.json, apps/verify-server/src/index.ts, packages/assets/src/index.ts, packages/rendering/.swcrc, packages/rendering/src/jsx/create-element.ts, packages/schemas/src/user/index.ts, packages/util/src/index.ts
* Add support for badges
* Add special footer for premium users
* Add support for Fragments in JSX
=> feat(profiles): add badges

apps/discord-bot/src/commands/test.command.ts, apps/discord-bot/src/commands/verify.command.ts, apps/discord-bot/src/components/Header/progression.ts, apps/discord-bot/src/services/api.service.ts, apps/discord-bot/src/services/i18next.service.ts, locales/en-US/discord-bot/default.json, packages/schemas/src/player/gamemodes/bedwars/index.ts, packages/schemas/src/player/gamemodes/bedwars/util.ts
* Added rank emojis
* Added localization to api service error messages
* Fixed bedwars level progression
* Fixed the function to render xpBars
=> feat(discord-bot): add rank emojis & localization to api service

apps/api/src/hypixel/hypixel.service.ts, apps/discord-bot/src/commands/base.hypixel-command.ts, apps/discord-bot/src/commands/copsandcrims/copsandcrims.command.tsx, packages/schemas/src/player/gamemodes/megawalls/kit.ts, packages/schemas/src/player/gamemodes/paintball/index.ts, packages/schemas/src/player/gamemodes/skywars/mode.ts, packages/schemas/src/player/gamemodes/skywars/util.ts, packages/schemas/src/player/gamemodes/smashheroes/index.ts, packages/schemas/src/player/gamemodes/smashheroes/mode.ts
add smash heroes kits
as well as fix some default value stuff
=> feat(smashheroes): add smash heroes kits

packages/schemas/src/player/gamemodes/murdermystery/mode.ts, packages/schemas/src/player/gamemodes/tntgames/mode.ts
=> fix(ratios): fix ratios for historical

apps/api/package.json, yarn.lock
=> revert(deps): update dependency point-of-view to v6

apps/api/src/guild/guild.controller.ts, apps/api/src/guild/guild.service.ts, apps/api/src/historical/historical.controller.ts, apps/api/src/historical/historical.service.ts, apps/api/src/player/player.controller.ts, apps/api/src/player/player.service.ts, apps/api/src/skin/skin.service.ts, apps/api/src/user/user.controller.ts, apps/api/src/user/user.service.ts, apps/api/tests/mocks/guild.mock.ts, apps/api/tests/mocks/historical.mock.ts, apps/api/tests/mocks/player.mock.ts, apps/api/tests/mocks/skin.mock.ts
=> refactor(api): rename methods on API service

apps/discord-bot/src/commands/info/help.command.ts, apps/discord-bot/src/commands/info/invite.command.ts, apps/discord-bot/src/commands/info/links.command.ts, apps/discord-bot/src/commands/info/ping.command.ts, locales/en-US/discord-bot/default.json
=> feat(commands): add info commands

apps/discord-bot/src/commands/general/general.profile.tsx, apps/discord-bot/src/commands/guild/guild.profile.tsx, apps/discord-bot/src/commands/pit/pit.command.tsx, apps/discord-bot/src/commands/pit/pit.profile.tsx, apps/discord-bot/src/components/Header/progression.ts, apps/discord-bot/src/services/api.service.ts, apps/discord-bot/src/services/pit-panda.service.ts, locales/en-US/discord-bot/default.json
finish pit command and fix tag parsing
=> fix(pit): finish pit command and fix tag parsing

apps/discord-bot/src/commands/watchdog.command.ts
=> feat(watchdog): add the watchdog stat command

apps/discord-bot/src/commands/reset.command.ts, apps/discord-bot/src/commands/socials/socials.command.ts, locales/en-US/discord-bot/default.json, locales/en-US/discord-bot/emojis.json
=> feat(commands): add /socials to view a player's socials

apps/discord-bot/src/commands/arcade/tables/dragon-wars.table.tsx, apps/discord-bot/src/commands/arcade/tables/football.table.tsx, apps/discord-bot/src/commands/arcade/tables/hide-and-seek.table.tsx, apps/discord-bot/src/commands/skywars/skywars.profile.tsx, apps/discord-bot/src/lib/command.listener.ts, apps/discord-bot/src/tips.ts, locales/en-US/default.json, packages/schemas/src/player/gamemodes/arcade/index.ts, packages/schemas/src/player/gamemodes/arcade/mode.ts
=> fix(misc): change colors, fix tips

.github/CONTRIBUTING.md, README.md
=> docs(readme): improve the readme and contributing files

apps/scripts/package.json, apps/scripts/src/limit-redis.js, pm2.config.js
=> chore(pm2): add a pm2 config file

apps/discord-bot/src/commands/quake/quake.profile.tsx, apps/discord-bot/src/components/Header/HistoricalHeader.tsx, packages/schemas/src/player/gamemodes/bedwars/index.ts, packages/schemas/src/player/gamemodes/bedwars/util.ts, packages/schemas/src/player/gamemodes/quake/mode.ts, packages/schemas/src/player/gamemodes/woolwars/index.ts, packages/schemas/src/player/gamemodes/woolwars/util.ts, packages/schemas/src/ratios.ts
=> fix(historical): fix historical leveling and ratios

pm2.config.js
=> chore(pm2): update pm2 config

apps/scripts/src/build-watch.js, packages/schemas/src/player/gamemodes/buildbattle/index.ts, packages/schemas/src/player/gamemodes/duels/mode.ts, packages/schemas/src/player/gamemodes/paintball/perks.ts, packages/schemas/src/player/gamemodes/quake/mode.ts, packages/schemas/src/player/gamemodes/skywars/index.ts, packages/schemas/src/player/gamemodes/skywars/mode.ts, packages/schemas/src/player/gamemodes/smashheroes/index.ts, packages/schemas/src/player/gamemodes/speeduhc/index.ts, packages/schemas/src/player/gamemodes/uhc/index.ts, packages/schemas/src/progression.ts, pm2.config.js
=> fix(schemas): add better default values

apps/discord-bot/src/commands/arenabrawl/arenabrawl.profile.tsx, apps/discord-bot/src/commands/buildbattle/buildbattle.profile.tsx, apps/discord-bot/src/commands/megawalls/megawalls.command.tsx, apps/discord-bot/src/commands/murdermystery/murdermystery.profile.tsx, apps/discord-bot/src/commands/paintball/paintball.profile.tsx, apps/discord-bot/src/commands/quake/quake.profile.tsx, apps/discord-bot/src/commands/speeduhc/speeduhc.profile.tsx, apps/discord-bot/src/commands/turbokartracers/turbokartracers.profile.tsx, apps/discord-bot/src/commands/uhc/uhc.profile.tsx, apps/discord-bot/src/commands/vampirez/vampirez.profile.tsx, apps/discord-bot/src/commands/walls/walls.profile.tsx, apps/discord-bot/src/components/Header/Header.tsx, apps/discord-bot/src/components/Historical/Historical-Header.tsx, locales/en-US/default.json, packages/schemas/src/player/gamemodes/arenabrawl/index.ts, packages/schemas/src/player/gamemodes/buildbattle/index.ts, packages/schemas/src/player/gamemodes/general/index.ts, packages/schemas/src/player/gamemodes/paintball/index.ts, packages/schemas/src/player/gamemodes/quake/index.ts, packages/schemas/src/player/gamemodes/turbokartracers/index.ts, packages/schemas/src/player/gamemodes/vampirez/index.ts, packages/schemas/src/player/gamemodes/walls/index.ts, packages/schemas/src/player/stats.ts, packages/schemas/src/player/util.ts
=> feat: add historical sidebar and classic tokens

apps/support-bot/src/commands/user.command.ts, apps/support-bot/src/events/guild-member-remove.event.ts, apps/support-bot/src/events/message-create.event.ts, apps/support-bot/src/services/ticket.service.ts
* Tickets would delete when a member left the server regardless if they were the owner of the ticket
=> fix(support-bot): tickets deleting when member leaves the server

apps/discord-bot/src/commands/arenabrawl/arenabrawl.profile.tsx, apps/discord-bot/src/commands/bedwars/bedwars.profile.tsx, apps/discord-bot/src/commands/buildbattle/buildbattle.profile.tsx, apps/discord-bot/src/commands/duels/bridge.profile.tsx, apps/discord-bot/src/commands/duels/duels.profile.tsx, apps/discord-bot/src/commands/guild/guild.profile.tsx, apps/discord-bot/src/commands/pit/pit.profile.tsx, apps/discord-bot/src/commands/skywars/skywars.profile.tsx, apps/discord-bot/src/commands/speeduhc/speeduhc.profile.tsx, apps/discord-bot/src/commands/uhc/uhc.profile.tsx, apps/discord-bot/src/commands/vampirez/vampirez.profile.tsx, apps/discord-bot/src/commands/woolwars/woolwars.profile.tsx, apps/discord-bot/src/services/pit-panda.service.ts, apps/support-bot/src/commands/commands.command.ts, locales/en-US/default.json, packages/rendering/src/font/font-renderer.ts, packages/schemas/src/friends/friend.ts, packages/schemas/src/player/gamemodes/blitzsg/index.ts, packages/schemas/src/player/gamemodes/turbokartracers/index.ts, packages/schemas/src/player/gamemodes/vampirez/life.ts, packages/schemas/src/player/gamemodes/vampirez/prefixes.ts, packages/schemas/src/player/gamemodes/walls/index.ts, packages/schemas/src/player/gamemodes/woolwars/index.ts, packages/schemas/src/player/gamemodes/woolwars/util.ts, packages/util/src/index.ts
=> fix(prefixes): fix coloring of prefixes and some misc changes

apps/discord-bot/src/commands/config/footer.sub-command-group.tsx, apps/discord-bot/src/commands/duels/tables/multi-duels-game-mode.table.tsx, apps/discord-bot/src/commands/duels/tables/single-duels-game-mode.table.tsx, apps/discord-bot/src/commands/duels/tables/uhc-duels.table.tsx, apps/discord-bot/src/commands/skywars/skywars.profile.tsx, packages/schemas/src/player/gamemodes/duels/index.ts, packages/schemas/src/player/gamemodes/duels/mode.ts
Removes kills from 
* Arena (kills are broken)
* Parkour
* BowSpleef
=> fix(duels): pvpless duels modes displaying kills in commands 

packages/schemas/src/metadata/metadata-scanner.ts, packages/schemas/src/player/gamemodes/general/challenges/index.ts
=> fix(challenges): fix MegaWalls & MurderMystery

apps/discord-bot/src/commands/historical/historical.base.tsx, apps/discord-bot/src/commands/pit/pit.profile.tsx, packages/schemas/src/player/gamemodes/pit/index.ts
=> feat(historical): add historical pit stats

packages/schemas/src/player/gamemodes/buildbattle/mode.ts, packages/schemas/src/player/gamemodes/general/challenges/index.ts
=> fix(buildbattle): remove repeating BB correct guesses

apps/api/src/historical/historical.controller.ts, apps/api/src/historical/historical.service.ts, apps/support-bot/src/commands/top-reset.command.ts, locales/en-US/default.json, packages/api-client/src/api.service.ts, packages/api-client/src/responses/get.historical-times.response.ts, packages/schemas/src/user/index.ts
=> feat(support): add /topreset to view the most common reset times

packages/schemas/src/player/gamemodes/murdermystery/index.ts, packages/schemas/src/player/gamemodes/murdermystery/mode.ts
=> fix(murdermystery): use correct survivor win stat

apps/support-bot/src/commands/top-reset.command.ts
=> fix(support-bot): removed % and total times from /topreset

apps/discord-bot/src/themes/boxes/hd.box.ts, apps/discord-bot/src/themes/boxes/uhd.box.ts, packages/rendering/src/font/font-renderer.ts
=> fix(boxes): fix themed boxes not making copies of border before mutating

apps/discord-bot/src/lib/command.listener.ts, apps/support-bot/src/lib/command.listener.ts, packages/discord/src/command/abstract-command.listener.ts
Closes #368 
Also re-enables premium command previews
=> fix(discord): use rest api to defer command interactions earlier

apps/discord-bot/src/commands/minecraft/server/server.command.tsx, apps/discord-bot/src/commands/minecraft/server/server.interface.ts, apps/discord-bot/src/commands/minecraft/server/server.profile.tsx, apps/discord-bot/src/components/Multiline.tsx, packages/rendering/src/components/Text.ts, packages/rendering/src/font/font-renderer.ts, packages/schemas/src/player/gamemodes/prefixes.ts, packages/schemas/src/player/gamemodes/walls/index.ts
* Fixes #379 
* Fixes #364 
* Fixes `/server` not using theming
=> fix: walls prefixes, /server themes, & /text \n issues

apps/discord-bot/src/commands/murdermystery/murdermystery.profile.tsx, packages/schemas/src/player/gamemodes/murdermystery/mode.ts
- Infection wins is completely broken
- Best time does not seem correct either
=> fix(murdermystery): remove infection wins and best time

apps/api/src/historical/historical.service.ts, apps/discord-bot/src/tips.ts, packages/schemas/src/player/gamemodes/challenges/index.ts, packages/schemas/src/util/leaderboard-scanner.ts, pm2.config.js
- Revert pm2 config
- Fix total challenges leaderboard `fieldName`
- Fix a few cases where `this` behaved strangely when using `additionalFields` and `extraDisplay`
- Disabled some tips on commands where they do not make sense
=> fix: misc issues from v0.9.0

packages/schemas/src/player/gamemodes/arcade/mode.ts
=> fix(pixelparty): correctly calulate normal and overall stats

apps/discord-bot/src/commands/status/status.profile.tsx, packages/schemas/src/game/game.ts
- Also fixed Tournament Lobby showing as undefined
=> feat(status): show last action for online players

apps/discord-bot/src/commands/duels/duels.profile.tsx, apps/discord-bot/src/commands/duels/tables/uhc-duels.table.tsx, apps/discord-bot/src/components/Table/TableData.tsx
=> feat(duels): add ws and kills to uhc duels profile

apps/discord-bot/src/commands/events/events.profile.tsx, packages/schemas/src/player/gamemodes/general/events.ts
=> feat(events): add christmas event stats

packages/schemas/src/player/gamemodes/smashheroes/index.ts
* Change Botman → Botmon
* Change Spoderman → Spooderman
=> fix(smashheroes): kit names

apps/discord-bot/src/commands/minecraft/text.command.tsx, packages/rendering/src/jsx/render.ts
- Adds text alignment option to `/text`
- Adds support for right alignment
=> feat(text): add alignment options to text command

apps/discord-bot/src/commands/leaderboards/player-leaderboard.command.ts
- also added a log for when a user tried to use historical lb
=> fix(server-mappings): revert server-mappings commit

apps/api/src/guild/guild.service.ts, apps/api/src/historical/leaderboards/historical-leaderboard.service.ts, apps/api/src/player/leaderboards/player-leaderboard.service.ts, apps/api/src/player/player.service.ts, apps/api/src/skin/skin.service.ts, apps/discord-bot/src/commands/guild/guild.command.tsx, apps/discord-bot/src/components/Header/Header.tsx, apps/discord-bot/src/components/List.tsx, apps/discord-bot/src/components/Sidebar.tsx, apps/discord-bot/src/components/Table/TableRow.tsx, packages/util/src/april-fools-color.ts, packages/util/src/april-fools.ts, packages/util/src/index.ts
=> feat: update designs for april fools

packages/schemas/src/player/gamemodes/skywars/util.ts
https://hypixel.net/threads/skywars-update-new-prestiges-qol-changes-balancing-and-bug-fixes-march-2023.5303364/
Description: Update and new SkyWars prestige colors
=> feat(skywars): update and add new SkyWars prestiges

packages/schemas/src/player/gamemodes/bedwars/util.ts
=> feat(bedwars): add new bedwars prestiges (3100-5000)

packages/schemas/src/player/gamemodes/megawalls/index.ts, packages/schemas/src/player/gamemodes/megawalls/kit.ts
- Fixed the following Mega Walls stats
- `finalDeaths`
- `witherDamage`
- `playtime`
- `points`
=> fix(megawalls): fix inaccurate megawalls stats 

apps/discord-bot/src/commands/socials/socials.command.ts, locales/en-US/emojis.json, packages/schemas/src/player/socials.ts
=> feat(socials): add tiktok and change twitter -> 𝕏

packages/schemas/src/player/gamemodes/quests/modes/bedwars.ts, packages/schemas/src/player/gamemodes/quests/modes/cops-and-crims.ts
=> feat(quests): add new bedwars and cops and crims quests

apps/discord-bot/src/commands/arenabrawl/arenabrawl.profile.tsx, packages/schemas/src/player/gamemodes/arenabrawl/index.ts, packages/schemas/src/player/gamemodes/arenabrawl/mode.ts
=> feat(arena brawl): add arena brawl winstreaks

README.md
Description:
**`README.md` was not updated with the past updates of Hypixel and Discord.**
Changed the way to get an API Key.
Updated Jacob's Discord with the new system.
N/A
=> chore(docs): update README.md with Hypixel and Discord changes

apps/discord-bot/src/commands/historical/historical.base.tsx, apps/discord-bot/src/commands/historical/session.command.tsx, apps/discord-bot/src/commands/megawalls/megawalls.command.tsx, apps/discord-bot/src/commands/megawalls/megawalls.profile.tsx, apps/discord-bot/src/commands/minecraft/text.command.tsx, apps/discord-bot/src/lib/convert-color-codes.ts, apps/support-bot/src/commands/tags.command.ts, package.json, packages/discord/src/services/api.service.ts, packages/schemas/src/metadata/metadata-scanner.ts, packages/schemas/src/player/gamemodes/megawalls/index.ts, packages/schemas/src/player/gamemodes/megawalls/kit.ts, pnpm-lock.yaml
- Add angel, dragon, and sheep kits
- Remove calculation for class points
- Closes #637
=> feat(megawalls): add new megawalls kits and update class points

packages/schemas/src/player/gamemodes/turbokartracers/index.ts
enable turbo kart racers gp tokens leaderboard
=> fix(tkr): enable turbo kart racers gp tokens leaderboard

apps/api/package.json, apps/discord-bot/package.json, apps/scripts/package.json, apps/site/package.json, apps/support-bot/package.json, packages/assets/package.json, packages/discord/package.json, packages/rendering/package.json, pnpm-lock.yaml
=> revert: "chore(deps): upgrade to skia-canvas 1.0"

packages/schemas/src/player/util.ts
=> feat(schemas): add tommy innit custom rank

apps/discord-bot/src/commands/duels/duels.profile.tsx, packages/schemas/src/player/gamemodes/duels/index.ts, packages/schemas/src/player/gamemodes/duels/mode.ts
=> feat(duels): add current kit and shots fired to sidebar

apps/discord-bot/src/commands/arcade/modes/hide-and-seek.tsx
=> fix: rearrange hide and seek stats

apps/verify-server/src/index.ts
- Online mode makes it so players are disconnected before receiving a code
=> fix(verify-server): disable online mode

apps/discord-bot/src/commands/status/status.profile.tsx, packages/schemas/src/player/status.ts
- Hypixel removed player's minecraft version from the API
=> fix: remove minecraft version from player status stats

.github/workflows/deploy.yml, apps/discord-bot/src/components/Footer.tsx, packages/schemas/src/player/gamemodes/general/events.ts, pnpm-lock.yaml
=> feat: add halloween logo, footer, background and events

apps/discord-bot/src/commands/murdermystery/murdermystery.profile.tsx, locales/en-US/default.json, packages/schemas/src/player/gamemodes/murdermystery/index.ts, packages/schemas/src/player/gamemodes/murdermystery/mode.ts
=> feat(murdermystery): add hero kills

apps/discord-bot/src/components/Footer.tsx
=> feat(winter): add slight winter theme

packages/schemas/src/player/gamemodes/buildbattle/index.ts
=> feat(buildbattle): update the new title changes

apps/discord-bot/src/commands/arcade/modes/hypixel-says.tsx, packages/schemas/src/player/gamemodes/arcade/mode.ts
=> feat(arcade): add santa says stats

apps/discord-bot/src/components/Footer.tsx, apps/discord-bot/src/themes/boxes/hd.box.ts, apps/discord-bot/src/themes/boxes/uhd.box.ts, packages/rendering/src/intrinsics/Box.ts, pnpm-lock.yaml
=> feat: add christmas theme

packages/schemas/src/player/gamemodes/woolgames/sheepwars.ts
Adds leaderboards for
- Explosive Kills
- Void Kills
- Bow Kills
- Melee Kills
=> feat(woolgames): add more sheep wars kills leaderboards

apps/discord-bot/src/themes/boxes/hd.box.ts, apps/discord-bot/src/themes/boxes/uhd.box.ts, packages/rendering/src/intrinsics/Box.ts, packages/skin-renderer/src/skin_loader.rs, pnpm-lock.yaml
- Use green and red to make the borders less distracting
=> feat(christmas): update christmas theme to be more accessible

apps/discord-bot/src/commands/tntgames/tntgames.profile.tsx, packages/schemas/src/player/gamemodes/tntgames/index.ts
=> feat(tntgames): add tntgames overview page and change page order

apps/discord-bot/src/commands/copsandcrims/copsandcrims.profile.tsx, locales/en-US/default.json, packages/schemas/src/player/gamemodes/copsandcrims/mode.ts
=> feat(copsandcrims): add grenade kills

apps/discord-bot/src/themes/boxes/hd.box.ts, apps/discord-bot/src/themes/boxes/uhd.box.ts, packages/rendering/src/intrinsics/Box.ts
=> fix: prevent box overlay from rendering twice

packages/schemas/src/player/gamemodes/tntgames/index.ts, packages/schemas/src/player/gamemodes/tntgames/mode.ts
=> fix(tntgames): storm wizard and arcane wizard stats

apps/discord-bot/src/commands/arcade/arcade.profile.tsx, apps/discord-bot/src/commands/arcade/modes/zombies.tsx, packages/schemas/src/player/gamemodes/arcade/mode.ts
=> fix(arcade): remove map difficulties from alien arcadium

apps/discord-bot/src/commands/quests/quests.command.tsx, apps/discord-bot/src/commands/quests/quests.profile.tsx, apps/discord-bot/src/commands/skywars/skywars.profile.tsx, apps/discord-bot/src/constants.ts, locales/en-US/default.json, packages/schemas/src/player/gamemodes/quests/index.ts, packages/schemas/src/player/gamemodes/quests/modes/skywars.ts, packages/schemas/src/player/gamemodes/quests/util.ts, packages/schemas/src/player/gamemodes/skywars/index.ts, packages/schemas/src/player/gamemodes/skywars/util.ts
=> feat(skywars): add new levelling and mini gamemode

packages/schemas/src/player/gamemodes/general/events.ts
=> feat(events): add easter 2025

packages/schemas/src/player/util.ts
https://hypixel.net/threads/team-update-one-unified-rank.5628609/#post-39522687
=> feat(schemas): add new hypixel staff rank

packages/schemas/src/player/gamemodes/general/events.ts
=> feat(events): summer 2025

apps/discord-bot/src/constants.ts, packages/schemas/src/player/gamemodes/duels/index.ts, packages/schemas/src/player/gamemodes/duels/mode.ts, packages/schemas/src/player/gamemodes/duels/util.ts, packages/util/src/minecraft-colors.ts
https://hypixel.net/threads/duels-v1-5-1-important-changes-bug-fixes.5980038/
- Add Default Prefix Scheme which restores old colors
- Half title requirements for Bridge, No Debuff, Parkour, Boxing, and Mega Walls
=> feat(duels): default scheme and halve win requirements for some modes

packages/schemas/src/player/gamemodes/duels/util.ts
=> feat(duels): add new og fade prefix scheme
