Statsify/statsify

- packages/schemas/src/player/gamemodes/speeduhc/index.ts
- packages/schemas/src/player/gamemodes/speeduhc/mode.ts
Added the assists stat to speed uhc, could be used later for Kills+Assists/Deaths ratio but for now is just a nice to have. Also added active mastery since it allows people to see what others are using.
> Add more SpeedUHC stats

- packages/schemas/src/player/gamemodes/megawalls/index.ts
- packages/schemas/src/player/gamemodes/megawalls/kit.ts
- packages/schemas/src/player/gamemodes/skywars/index.ts
This pull request aims to overhaul mega walls stats to include kits and have the capability for kits leaderboards. However some discussion is needed before I mark this as ready to merge.
There is an issue of I am not sure how to structure the class with the kits, there can be a class with the overall stats separate from the rest of the kits with the total stats. Or it can be kept as is with only adding the kits to the `MegaWalls` class. I will await review before marking as ready to merge as I do think this needs some discussion.
> Add megawalls kit stats

- packages/schemas/src/player/gamemodes/warlords/index.ts
Description: Warlord losses in API are only about 90% accurate, this PR tries to improve this as much as possible.
> fix(warlords): Fix Warlords losses

- apps/api/src/guild/guild.controller.ts
- apps/api/src/guild/leaderboards/guild-leaderboard.controller.ts
- apps/api/src/historical/historical.controller.ts
- apps/api/src/hypixel-resources/hypixel-resources.controller.ts
- apps/api/src/player/leaderboards/player-leaderboard.controller.ts
- apps/api/src/player/player.controller.ts
- apps/api/src/skin/skin.controller.ts
Tags make the different category of endpoints into menus in swagger and redoc.
This is desirable due to the large amount of endpoints available with the various http methods as well.
Swagger tags documentation can be viewed [here](https://swagger.io/docs/specification/grouping-operations-with-tags/).
> feat(redoc): add tags to each endpoint

- packages/schemas/src/player/gamemodes/quake/mode.ts
In Quakecraft, there is not a tangible method to obtain a W/L ratio. As a result, almost all players have adopted the KWR stat in order to measure win rate instead. This is due to the fact that the way Quake works, it takes 25 kills to win a game, every single time. As a result, seeing how many kills it takes a person to obtain one win is a very accurate way to measure win rate in the absence of a true win/loss ratio. The Quake community has greatly requested this ratio, and adding it will greatly enhance the experience of those using the Quake command as it allows them to measure success in ways they were unable to using the bot before. This is a highly valued stat for many.
> fix(schema): add duels coins

- apps/discord-bot/src/commands/quake/quake.profile.tsx
- apps/discord-bot/src/commands/status/status.profile.tsx
- locales/en-US/default.json
- packages/schemas/src/player/gamemodes/arcade/mode.ts
- packages/schemas/src/player/gamemodes/general/index.ts
- packages/schemas/src/player/gamemodes/murdermystery/mode.ts
- packages/schemas/src/player/gamemodes/quake/mode.ts
- packages/schemas/src/ratios.ts
> fix(v0.2.0): fix bugs in v0.2.0 and add some LBs

- apps/api/src/leaderboards/leaderboard.service.ts
- Leaderboard expire times were being returned in milliseconds meanwhile redis expected them in seconds
> fix(leaderboards): leaderboard expire times 

- packages/schemas/src/player/gamemodes/pit/util.ts
Description: Replaces current green brackets (placeholder) with black brackets (the actual in-game color).
> fix(pit): Added correct prestige color to p45-49.

- apps/discord-bot/src/commands/minecraft/cape.command.ts
> fix(capes): remove blank whitespace at the bottom of cape images

- packages/schemas/src/player/gamemodes/uhc/index.ts
- Hypixel made the UHC submodes have underscores in their key names so the stats weren't counting
> fix(uhc): submodes stats not counting

- apps/discord-bot/src/commands/megawalls/megawalls.command.tsx
- packages/schemas/src/player/gamemodes/prefixes.ts
- Correctly rounds prefixes if there is a prefix that is not a multiple of 10
- Fixes missing mega walls kit in dropdown
Old
New
> fix: rounding of prefixes that aren't multiples of 10

- packages/schemas/src/player/gamemodes/woolwars/util.ts
Fixes the extra Unicode characters as seen in the image.
> fix(woolwars): remove extra characters from prestige icons

- apps/discord-bot/src/commands/config/badge.command.tsx
- apps/discord-bot/src/commands/config/theme.command.tsx
> fix(config): make config commands use proper localization string

- apps/discord-bot/src/commands/bedwars/bedwars.profile.tsx
- apps/discord-bot/src/commands/duels/bridge.profile.tsx
- apps/discord-bot/src/commands/duels/duels.profile.tsx
- apps/discord-bot/src/commands/murdermystery/murdermystery.profile.tsx
- apps/discord-bot/src/commands/skywars/skywars.profile.tsx
- packages/schemas/src/player/gamemodes/bedwars/index.ts
- packages/schemas/src/player/gamemodes/duels/index.ts
- packages/schemas/src/player/gamemodes/murdermystery/index.ts
- packages/schemas/src/player/gamemodes/skywars/index.ts
- packages/skin-renderer/Cargo.toml
- Completely remove loot chests
- Rename coins to tokens for Bed Wars, Duels, and Murder Mystery
> feat: rename coins -> tokens and remove loot chests

- packages/schemas/src/player/gamemodes/megawalls/kit.ts
Properly counts mega walls playtime, currently is sort of "double counting"
Closes #613
> fix(megawalls): fix megawalls playtime

- apps/api/src/leaderboards/leaderboard.service.ts
- apps/discord-bot/src/commands/leaderboards/guild-leaderboard.argument.ts
- apps/discord-bot/src/commands/leaderboards/player-leaderboard.argument.ts
- packages/schemas/src/util/leaderboard-scanner.ts
Currently, if a player is wiped and their stats reset to 0, they won't be removed from leaderboards. This fixes that.
> fix(leaderboards): remove wiped players from leaderboards

- apps/discord-bot/src/commands/minecraft/uuid.command.ts
Currently both uuids in `/uuid` have no dashes. This fixes that.
> fix(disocrd-bot): dashed uuid format in /uuid

- apps/discord-bot/src/commands/woolgames/woolgames.profile.tsx
- locales/en-US/default.json
- packages/schemas/src/player/gamemodes/woolgames/index.ts
- packages/schemas/src/player/gamemodes/woolgames/sheepwars.ts
- packages/schemas/src/player/stats.ts
> feat: add sheep killed to sheep wars stats

- packages/schemas/src/player/gamemodes/tntgames/mode.ts
> fix(tntgames): convert wizards air time from ticks to ms

- apps/discord-bot/src/commands/events/event-colors.ts
- apps/discord-bot/src/commands/events/events.profile.tsx
- apps/discord-bot/src/commands/general/historical-general.profile.tsx
- packages/schemas/src/player/gamemodes/general/events.ts
> fix(discord-bot): show latest event's exp in session general stats

- .gitignore
- apps/discord-bot/src/commands/minecraft/text.command.tsx
- apps/site/next-env.d.ts
- packages/rendering/src/font/font-renderer.ts
- packages/schemas/src/player/gamemodes/quests/util.ts
- packages/schemas/src/player/gamemodes/skywars/util.ts
> fix(discord-bot): incorrect width unicode underline and strikethroughs
